/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UserContract__factory } from "./UserContract__factory";
export { UserInfo__factory } from "./UserInfo__factory";
